export const CONFIG = {
  SUPABASE_URL: process.env.EXPO_PUBLIC_SUPABASE_URL ?? '',
  SUPABASE_ANON_KEY: process.env.EXPO_PUBLIC_SUPABASE_ANON_KEY ?? '',

  SOS_COUNTDOWN_SECONDS: 3,
  INVITATION_EXPIRY_HOURS: 72,
  INVITATION_CODE_LENGTH: 6,

  LOCATION_ACCURACY: 'high' as const,
  SOS_LOCATION_INTERVAL_MS: 5000,

  MAX_GROUP_NAME_LENGTH: 60,
  MAX_GROUP_DESC_LENGTH: 200,
};
