export const STRINGS = {
  AUTH: {
    LOGIN_TITLE: 'Bienvenido de vuelta',
    LOGIN_SUBTITLE: 'Inicia sesión para continuar',
    REGISTER_TITLE: 'Crear cuenta',
    REGISTER_SUBTITLE: 'Únete a REPÓRTATE',
    FORGOT_PASSWORD_TITLE: '¿Olvidaste tu contraseña?',
    FORGOT_PASSWORD_SUBTITLE: 'Te enviaremos un enlace para recuperarla',
    EMAIL_LABEL: 'Correo electrónico',
    EMAIL_PLACEHOLDER: 'tu@correo.com',
    PASSWORD_LABEL: 'Contraseña',
    PASSWORD_PLACEHOLDER: 'Mínimo 8 caracteres',
    FULL_NAME_LABEL: 'Nombre completo',
    FULL_NAME_PLACEHOLDER: 'Tu nombre y apellido',
    LOGIN_BUTTON: 'Iniciar sesión',
    REGISTER_BUTTON: 'Crear cuenta',
    RESET_BUTTON: 'Enviar enlace',
    FORGOT_PASSWORD_LINK: '¿Olvidaste tu contraseña?',
    NO_ACCOUNT: '¿No tienes cuenta? ',
    REGISTER_LINK: 'Regístrate',
    HAVE_ACCOUNT: '¿Ya tienes cuenta? ',
    LOGIN_LINK: 'Inicia sesión',
    BACK_TO_LOGIN: 'Volver al inicio de sesión',
    RESET_SENT: 'Revisa tu correo para el enlace de recuperación',
  },
  HOME: {
    TITLE: 'Mi Jornada',
    JOURNEY_START_BUTTON: 'Iniciar jornada',
    JOURNEY_END_BUTTON: 'Finalizar jornada',
    SOS_BUTTON: 'SOS Emergencia',
    JOURNEY_STARTED: 'Jornada iniciada',
    JOURNEY_ENDED: 'Jornada finalizada',
    NO_GROUP: 'No perteneces a ningún grupo',
    NO_GROUP_ACTION: 'Únete a un grupo con un código de invitación',
    SELECT_GROUP: 'Seleccionar grupo',
    STARTED_AT: 'Iniciada a las',
  },
  GROUP: {
    TITLE: 'Mi Grupo',
    MEMBERS: 'Miembros',
    NO_MEMBERS: 'No hay miembros en este grupo',
    CREATE_GROUP: 'Crear grupo',
    JOIN_GROUP: 'Unirse con código',
    GROUP_NAME_LABEL: 'Nombre del grupo',
    GROUP_NAME_PLACEHOLDER: 'Ej. Equipo de seguridad norte',
    GROUP_DESC_LABEL: 'Descripción (opcional)',
    GROUP_DESC_PLACEHOLDER: 'Describe el propósito del grupo',
    CREATE_BUTTON: 'Crear grupo',
    INVITE_TITLE: 'Invitar miembros',
    INVITE_CODE: 'Código de invitación',
    INVITE_CODE_COPIED: 'Código copiado',
    INVITE_EXPIRES: 'Expira en',
    GENERATE_INVITE: 'Generar código',
    JOIN_TITLE: 'Unirse a un grupo',
    JOIN_CODE_PLACEHOLDER: 'Ingresa el código de 6 caracteres',
    JOIN_BUTTON: 'Unirse al grupo',
    ABSENCE_ALERT_TITLE: 'Alerta de ausencia',
    ABSENCE_ALERT_BODY: 'Los siguientes miembros no han finalizado su jornada:',
    SEND_ALERT: 'Enviar alerta',
    NO_ABSENCES: 'Todos los miembros han finalizado su jornada',
    CAPTAIN_BADGE: 'Capitán',
    STATUS_ACTIVE: 'En jornada',
    STATUS_ENDED: 'Jornada finalizada',
    STATUS_NONE: 'Sin reporte hoy',
  },
  SOS: {
    TITLE: 'SOS Emergencia',
    SUBTITLE: 'Activa esta alerta solo en caso de emergencia real',
    BUTTON_LABEL: 'EMERGENCIA',
    CONFIRM_TITLE: '¿Activar alerta SOS?',
    CONFIRM_BODY: 'Se notificará a todos los miembros de tu grupo con tu ubicación en tiempo real.',
    CONFIRM_BUTTON: 'Activar SOS',
    CANCEL_BUTTON: 'Cancelar',
    COUNTDOWN: 'Activando en',
    ACTIVE_TITLE: 'Alerta SOS activa',
    ACTIVE_BODY: 'Tu ubicación se está compartiendo con tu grupo',
    DEACTIVATE_BUTTON: 'Desactivar SOS',
    DEACTIVATE_CONFIRM: '¿Confirmas que la emergencia terminó?',
    RESOLVED: 'Alerta SOS desactivada',
  },
  PROFILE: {
    TITLE: 'Mi perfil',
    EDIT_PHOTO: 'Cambiar foto',
    LOGOUT: 'Cerrar sesión',
    LOGOUT_CONFIRM: '¿Cerrar sesión?',
    MY_GROUPS: 'Mis grupos',
    VERSION: 'Versión',
  },
  NOTIFICATIONS: {
    JOURNEY_START: '{name} ha iniciado su jornada',
    JOURNEY_END: '{name} ha finalizado su jornada',
    SOS_ACTIVATED: '🆘 {name} ha activado una alerta de emergencia',
    SOS_RESOLVED: '{name} ha desactivado la alerta SOS',
    ABSENCE_ALERT: 'Miembros sin reporte de cierre',
  },
  ERRORS: {
    GENERIC: 'Ocurrió un error. Intenta de nuevo.',
    NETWORK: 'Sin conexión. Verifica tu red.',
    INVALID_EMAIL: 'Correo electrónico inválido',
    WEAK_PASSWORD: 'La contraseña debe tener al menos 8 caracteres',
    REQUIRED: 'Este campo es obligatorio',
    INVALID_CODE: 'Código de invitación inválido o expirado',
    LOCATION_DENIED: 'Activa los permisos de ubicación en configuración',
    NOTIFICATION_DENIED: 'Activa las notificaciones en configuración',
    JOURNEY_ALREADY_STARTED: 'Ya iniciaste tu jornada hoy',
    NO_ACTIVE_JOURNEY: 'Debes iniciar tu jornada primero',
  },
  COMMON: {
    LOADING: 'Cargando...',
    RETRY: 'Reintentar',
    SAVE: 'Guardar',
    CANCEL: 'Cancelar',
    CONFIRM: 'Confirmar',
    DELETE: 'Eliminar',
    BACK: 'Volver',
    DONE: 'Listo',
    OR: 'o',
    YES: 'Sí',
    NO: 'No',
  },
};
